### ISSUE TITLE
Automatic Word-Wrap: Break lines at screen edge not at minimap edge

### ISSUE THREAD

**Issue by broesmel** [BenRogersWPG/VSCode-Transparent-Minimap#209]
**Is your feature request related to a problem? Please describe.**
Currently, VS Code's auto code wrap wraps the code before the border of the minimap. With this extension, to utilize the additional horizontal space (whilst also keeping all of the code in view via wrapping), the auto wrap margin would also have to be moved.

**Describe the solution you'd like**
Make the VS Code auto code wrap wrap at theview edge not the minimap edge.

**Comment by BenRogersWPG** [comment]
Hi @broesmel, 
Thanks for the issue. 

I will be looking into this. 

I believe you must be referring to files like `.md` (Markdown) and such right?
So far, I have only had those type of files not work with the wrapping. The extensions still works, but no space is "gained" on those type of files. 

Are you experiencing any other filetypes that have this side effect?

Either way, I will look into the bug more, and look towards fixing this.
Thanks!

**Comment by broesmel** [comment]
Thanks for the quick reply! 

I have it in a codebase of mainly python (.py) files, but afaik it happens for all files in my setup. Even if adjusting the minimap width, the word-wrap break always happens at the assigned minimap width. Even if having the minimap completely hidden unless on hover. I have attached Images to illustrate.

![With word-wrap disabled: Transparency in effect](https://github.com/BenRogersWPG/VSCode-Transparent-Minimap/assets/23656696/7a714176-b65a-408f-a76a-576e3d32eff3)

![With word-wrap enabled: Breaks before the minimap](https://github.com/BenRogersWPG/VSCode-Transparent-Minimap/assets/23656696/b766d539-c7d7-4602-b0ed-c9cae1ba5424)



Thanks!

**Comment by BenRogersWPG** [comment]
Hi @broesmel 
Thanks for the screenshots. 

I believe I was able to find the settings to help you. 

I was able to get Word Wrap to toggle on/off while still displaying behind the minimap by setting these two settings:

### `editor.wordWrap`
_set to `wordWrapColumn`_

### `editor.wordWrapColumn`
_set to `221` 
(this needs to be set for the monitor you are using. The wrap point should occur just at the end of the screen, so you can read all characters. Play around with this setting by increasing / decreasing it to have it display just right)_

![word wrap settings](https://github.com/BenRogersWPG/VSCode-Transparent-Minimap/assets/2609214/5841d822-c0f9-449d-8000-9d2e386d5598)

Then to turn off, you would simply set `editor.wordWrap` to `off`

If these don't work for you, I can look more into coding this on the extension, but I am not entirely sure it is an extension problem - it could most likely be a setting for you 😁

**Comment by broesmel** [comment]
Hi, thanks a lot for the feedback and looking it oit!

This works but really not only per monitor but per window size. As soon as the sidebar is resized, or you half the code view to view files side by side, you really want the width to be based on the viewport, including the minimap space gained. 

If this is your intended use case for this extension then of course that's fine! But I was looking for something that would take of this automatically.

Best,

**Comment by BenRogersWPG** [comment]
After much investigation, I have concluded that this is unfortunately a user-specific issue and not something really _fixable_ through the code on my extension.

I thank you again for the great detail and information, but it just comes down to the fact that everyone's monitors and editor setups are different - as well as if VSCode is maximized, split screen, etc. as well. 

I hope you are still able to enjoy the extension, and feel free to propose other features if you ever come across good ideas!

All the best, and happy coding!
👍🏻
