### ISSUE TITLE
Request: show on selection 

### ISSUE THREAD

**Issue by Tobbyte** [BenRogersWPG/VSCode-Transparent-Minimap#577]
Hey there,
came here in search for a feature for the minimap and maybe you're interested:
My main use of the minimap is to see references of a selection at a glance; so f.e. when double clicked a word or the results from a search. Per default a search result is highlighted in orange, see image:
<img width="120" alt="Bildschirmfoto 2024-07-23 um 15 50 19" src="https://github.com/user-attachments/assets/f888b3c9-bcd9-4eb5-a089-02b2090612fa">

To not give up on too much screen space, I'd like the minimap to auto-hide (or to be transparent, thanks to your work!) like the default setting *but* always be visible (or solid) when a word is selected or when there are highlights from a search.

**Describe the solution you'd like**
Minimap should be solid or visible (when auto hidden) when word or search result is highlighted.

cheers and thanks for your work! 👋

**Comment by BenRogersWPG** [comment]
Hi @Tobbyte, 

Great suggestion! I like this idea!

Thank you, I will try working on this!

**Comment by Tobbyte** [comment]
Hey Ben, took the opportunity to write my own first extension :) https://github.com/Tobbyte/MiniGlimpse
🖖

**Comment by BenRogersWPG** [comment]
> Hey Ben, took the opportunity to write my own first extension :) https://github.com/Tobbyte/MiniGlimpse 🖖


**NO WAY!** That is amazing!
Nice going!

Do you think I can close this Issue?
**Or,** 
Perhaps you want to incorporate it into this extension in a pull request. 

I feel they might be good as separate entities, but happy to hear what you think. 

Once I push a next version, I will be sure to link to your extension!
In the meantime, I will try yours out!

Congratulations. 
🎉

**Comment by Tobbyte** [comment]
Hey Ben, thanks for the compliments!

I also think it’s (still) better to keep it separate for now.
But speaking of which: have you found a way to make the minimap clickable-through, maybe? From what I’ve gathered, making changes directly in the DOM isn’t exactly something the developers endorse—in fact, quite the opposite...

I absolutely love the semi-transparent effect, but it always makes me want to click on that area, which kind of defeats the purpose (for me, at least).

(oh and sure close this issue) :)
🖖

**Comment by BenRogersWPG** [comment]
> Hey Ben, thanks for the compliments!
> 
> I also think it’s (still) better to keep it separate for now. But speaking of which: have you found a way to make the minimap clickable-through, maybe? From what I’ve gathered, making changes directly in the DOM isn’t exactly something the developers endorse—in fact, quite the opposite...
> 
> I absolutely love the semi-transparent effect, but it always makes me want to click on that area, which kind of defeats the purpose (for me, at least).
> 
> (oh and sure close this issue) :) 🖖

Very good point!

I have not found a way to do this quite yet! But can keep experimenting!
Thank you!

**Comment by BenRogersWPG** [comment]
Fixed by @Tobbyte via the extension - [Tobbyte.mini-glimpse](https://marketplace.visualstudio.com/items?itemName=Tobbyte.mini-glimpse) 👏

* In my upcoming release, I will add a project recommendation to this extension 🙂
