### ISSUE TITLE
resize width

### ISSUE THREAD

**Issue by DamienLopvet** [BenRogersWPG/VSCode-Transparent-Minimap#83]
Hi there, 
I'dd like to be able to resize the width of the minimap view.
Can you do that ?

Anyway, thank you for your work, I appriciate!

Best reagards
Damien from France

**Comment by BenRogersWPG** [comment]
> Hi there, I'dd like to be able to resize the width of the minimap view. Can you do that ?
> 
> Anyway, thank you for your work, I appriciate!
> 
> Best reagards Damien from France

Hi Damien,

Thanks so much for the question, and so glad you have been enjoying the extension. 

As for your request, it is actually already baked into VS Code. 

Please have a look at the Settings and search for `editor.minimap.maxColumn`:
![Screenshot of VS Code settings for editor.minimap.maxColumn showing default value of 120](https://user-images.githubusercontent.com/2609214/207476262-678f4a83-7d37-4a07-bf2e-316059947368.png)

Setting this under 120 results in a narrow minimap, and setting it higher (for example 300) results in a wider minimap.

Let me know if there is anything more I can look at!
All the best!

**Comment by DamienLopvet** [comment]
Thank you Roger, It works like a charm, I appreciate it a lot .


Le mer. 14 déc. 2022 à 01:43, Ben Rogers ***@***.***> a
écrit :
